services:
  slasha:
    build:
      context: .
      dockerfile: Dockerfile
    image: slasha:latest
    container_name: slasha
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - slasha-data:/home/slasha/.slasha
      - slasha-ssh:/home/slasha/.ssh
    env_file:
      - .env
    restart: unless-stopped

volumes:
  slasha-data:
  slasha-ssh:
