// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlertChannel = {
  id: string;
  name: string;
  config: AlertChannelConfig;
  enabled: boolean;
  created_at: string;
  updated_at: string;
};

export type AlertChannelConfig =
  | { kind: 'slack'; webhook_url: string }
  | { kind: 'telegram'; bot_token: string; chat_id: string };

export type AlertIncident = {
  id: string;
  rule_id: string;
  target_key: string;
  status: AlertIncidentStatus;
  trigger_value: number | null;
  current_value: number | null;
  recovery_value: number | null;
  threshold_value: number | null;
  opened_at: string;
  last_notified_at: string | null;
  resolved_at: string | null;
};

export type AlertIncidentStatus = 'open' | 'resolved';

export type AlertNotification = {
  id: string;
  incident_id: string;
  kind: AlertNotificationKind;
  message: string;
  created_at: string;
};

export type AlertNotificationKind = 'triggered' | 'renotified' | 'resolved';

export type AlertRule = {
  id: string;
  name: string;
  config: AlertRuleConfig;
  channel_ids: Array<string>;
  direct_webhook_url: string | null;
  message_template: string | null;
  shell_command: string | null;
  enabled: boolean;
  cooldown_secs: number;
  created_at: string;
  updated_at: string;
};

export type AlertRuleConfig =
  | { kind: 'server_cpu'; threshold_percent: number }
  | { kind: 'server_memory'; threshold_percent: number }
  | { kind: 'server_load_average'; threshold: number }
  | { kind: 'app_cpu'; app_id: string; threshold_percent: number }
  | { kind: 'app_memory'; app_id: string; threshold_percent: number }
  | { kind: 'domain_tls_expiry'; domain: string; days_before: number }
  | { kind: 'domain_dns_misconfigured'; domain: string };
