// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlertRuleInput = {
  name: string;
  enabled: boolean;
  target: string;
  event: string;
  params: string;
  cooldown_secs: number;
  action_type: string;
  action_config: string;
};
