// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppBackup = { id: string, app_id: string, enabled: boolean, db_path: string, bucket: string, endpoint: string, path_prefix: string | null, access_key_id: string, secret_access_key: string, restore_pending: boolean, last_synced_at: string | null, created_at: string, updated_at: string, last_checked_at: string | null, last_check_ok: boolean | null, last_check_error: string | null, };
