// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppMetrics = {
  id: string;
  app_id: string;
  cpu_usage: number;
  memory_used: number;
  memory_limit: number;
  network_rx_bps: number;
  network_tx_bps: number;
  disk_read_bps: number;
  disk_write_bps: number;
  created_at: string;
};
