// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type App = { id: string, slug: string, name: string, repo_path: string, default_branch: string, status: string, created_at: string, };

export type AppMember = { app_id: string, user_id: string, role: string, added_at: string, };
