// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type App = {
  id: string;
  slug: string;
  name: string;
  repo_path: string;
  default_branch: string;
  created_at: string;
  auto_deploy: boolean;
  source: AppSource;
  node_id: string;
};

export type AppDomain = {
  id: string;
  app_id: string;
  domain: string;
  created_at: string;
};

export type AppEnvVar = {
  id: string;
  app_id: string;
  key: string;
  value: string;
  created_at: string;
  updated_at: string;
};

export type AppMember = {
  app_id: string;
  user_id: string;
  role: AppMemberRole;
  added_at: string;
};

export type AppMemberRole = 'Owner' | 'Admin' | 'Member';

export type AppSource = 'local' | 'github' | 'git';
