// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppScale = { id: string, app_id: string, process_type: ProcessType, desired: number, };

export type ProcessContainer = { name: string, process_type: ProcessType, instance_index: number, status: ProcessStatus, };

export type ProcessStatus = "Running" | "Stopped";

export type ProcessType = "web" | "worker" | "release";
