// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionStatus = "connected" | "disconnected";

export type GitConnection = { app_id: string, clone_url: string, created_at: string, };

export type GithubConnection = { app_id: string, installation_id: bigint, repository_id: bigint, status: ConnectionStatus, created_at: string, updated_at: string, };

export type GithubInstallation = { user_id: string, installation_id: bigint, created_at: string, };
