// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CronJob = {
  id: string;
  app_id: string;
  name: string;
  schedule: string;
  command: string;
  timezone: string;
  enabled: boolean;
  timeout_secs: number;
  runtime: CronRuntime;
  last_run_at: string | null;
  next_run_at: string | null;
  created_at: string;
  updated_at: string;
};

export type CronRun = {
  id: string;
  cron_job_id: string;
  status: CronRunStatus;
  trigger_kind: CronRunTrigger;
  exit_code: number | null;
  error: string | null;
  started_at: string | null;
  finished_at: string | null;
  created_at: string;
};

export type CronRunStatus =
  | 'pending'
  | 'running'
  | 'succeeded'
  | 'failed'
  | 'timed_out'
  | 'skipped';

export type CronRunTrigger = 'scheduled' | 'manual';

export type CronRuntime = 'app' | 'utility';
