// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Deployment = {
  id: string;
  app_id: string;
  commit_sha: string;
  commit_message: string;
  status: DeploymentStatus;
  created_at: string;
  updated_at: string;
  node_id: string;
};

export type DeploymentStatus =
  | 'Pending'
  | 'Building'
  | 'Running'
  | 'Failed'
  | 'Stopped';
