// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogPrefix =
  | 'system'
  | { web: number }
  | { worker: number }
  | 'service'
  | { custom: string };

export type LogRecord = {
  id: string;
  timestamp: string;
  resource_kind: ResourceKind;
  resource_id: string;
  app_id: string | null;
  prefix: LogPrefix | null;
  stream: LogStream;
  message: string;
};

export type LogStream = 'stdout' | 'stderr';

export type ResourceKind =
  | 'deployment'
  | 'service'
  | 'cron'
  | 'node_setup'
  | 'node_teardown';
