// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Node = {
  id: string;
  name: string;
  host: string | null;
  user: string | null;
  port: number | null;
  ssh_private_key: string | null;
  internal_root_ca: string | null;
  status: NodeStatus;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};

export type NodeStatus = 'SettingUp' | 'Ready' | 'Error' | 'Deleting';
