// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeMetrics = {
  id: string;
  cpu_usage: number;
  memory_used: bigint;
  memory_total: bigint;
  swap_used: bigint;
  swap_total: bigint;
  disk_used: bigint;
  disk_total: bigint;
  network_rx_bps: number;
  network_tx_bps: number;
  load_average: number;
  node_id: string;
  created_at: string;
};
