// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type S3Storage = {
  id: string;
  name: string;
  endpoint: string;
  bucket: string;
  region: string;
  access_key_id: string;
  force_path_style: boolean;
  created_at: string;
  updated_at: string;
};
