// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerMetrics = { id: string, cpu_usage: number, memory_used: number, memory_total: number, swap_used: number, swap_total: number, disk_used: number, disk_total: number, network_rx_bps: number, network_tx_bps: number, load_average: number, created_at: string, };
