// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Service = {
  id: string;
  app_id: string;
  kind: ServiceKind;
  name: string;
  version: string;
  status: ServiceStatus;
  created_at: string;
  updated_at: string;
};

export type ServiceEnvVar = {
  id: string;
  service_id: string;
  key: string;
  value: string;
  created_at: string;
  updated_at: string;
};

export type ServiceKind = 'PostgreSQL' | 'MySQL' | 'MongoDB' | 'Redis';

export type ServiceStatus = 'Provisioning' | 'Running' | 'Stopped' | 'Failed';
