// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServiceBackup = {
  id: string;
  service_id: string;
  s3_storage_id: string | null;
  file_name: string;
  file_size: bigint;
  status: ServiceBackupStatus;
  trigger_kind: ServiceBackupTrigger;
  error: string | null;
  stored_locally: boolean;
  last_restored_at: string | null;
  restore_status: ServiceRestoreStatus;
  restore_error: string | null;
  created_at: string;
};

export type ServiceBackupConfig = {
  service_id: string;
  enabled: boolean;
  schedule: string;
  timezone: string;
  retention_count: number;
  s3_storage_id: string | null;
  keep_local: boolean;
  last_run_at: string | null;
  next_run_at: string | null;
  created_at: string;
  updated_at: string;
};

export type ServiceBackupStatus = 'running' | 'succeeded' | 'failed';

export type ServiceBackupTrigger = 'scheduled' | 'manual';

export type ServiceRestoreStatus =
  | 'idle'
  | 'restoring'
  | 'succeeded'
  | 'failed';
