// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerSettings = {
  id: string;
  cpu_limit_percent: number | null;
  memory_limit_percent: number | null;
  disk_limit_percent: number | null;
  slack_webhook_url: string | null;
  updated_at: string;
};
