// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SshKey = { id: string, user_id: string, title: string | null, public_key: string, created_at: string, };
