export function LayoutGrid(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect
        x="3"
        y="3"
        width="7"
        height="7"
        rx="1.5"
        fill="currentColor"
      ></rect>
      <rect
        x="14"
        y="3"
        width="7"
        height="7"
        rx="1.5"
        fill="currentColor"
      ></rect>
      <rect
        x="3"
        y="14"
        width="7"
        height="7"
        rx="1.5"
        fill="currentColor"
      ></rect>
      <rect
        x="14"
        y="14"
        width="7"
        height="7"
        rx="1.5"
        fill="currentColor"
      ></rect>
    </svg>
  );
}
